# -*- coding: utf-8 -*-
"""ai.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sZWD8C12zpRKUuHefRT8sdrjhnhrA42B
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

"""SECTION 1: LOAD & INSPECT"""

df = pd.read_csv("ai_job_replacement_2020_2026.csv")

df.head()

df.info()

df.describe()

df.dtypes

"""SECTION 2: DATA CLEANING"""

df.isnull().sum()

df.duplicated().sum()

"""SECTION 3: Automation Risk % Distribution"""

plt.hist(df["automation_risk_percent"],
bins=20, color="teal",edgecolor="white")
plt.title("Automation Risk % Distribution")
plt.xlabel("Automation Risk %")
plt.ylabel("Frequency")
plt.show()

"""SECTION 4: AI Replacement Score Distribution"""

plt.hist(df["ai_replacement_score"],
bins=20, color="tomato", edgecolor="white")
plt.title("AI Replacement Score Distribution")
plt.xlabel("AI Replacement Score")
plt.ylabel("Frequency")
plt.show()

"""SECTION 5: Risk Category Frequency"""

order  = ["Low", "Medium", "High"]
colors = ["green", "orange", "red"]
counts = df["automation_risk_category"].value_counts().reindex(order)

plt.bar(counts.index, counts.values,
color=colors, edgecolor="white")
plt.title("Risk Category — Frequency")
plt.ylabel("Count")
plt.show()

"""SECTION 6: AI Replacement Score by Industry"""

industry_score = df.groupby("industry")["ai_replacement_score"].mean().sort_values(ascending=True)

plt.barh(industry_score.index, industry_score.values, color="teal", edgecolor="white")
plt.title("Average AI Replacement Score by Industry")
plt.xlabel("AI Replacement Score")
plt.show()

"""SECTION 7:  Automation Risk % by Country"""

country_risk = df.groupby("country")["automation_risk_percent"].mean().sort_values(ascending=True)

plt.barh(country_risk.index, country_risk.values, color="coral", edgecolor="white")
plt.title("Average Automation Risk % by Country")
plt.xlabel("Automation Risk %")
plt.show()

"""SECTION 8: Salary Change % by Country"""

salary_country = df.groupby("country")["salary_change_percent"].mean().sort_values()

colors_sal = ["red" if v < 0 else "green" for v in salary_country.values]

plt.barh(salary_country.index, salary_country.values,
         color=colors_sal, edgecolor="white")
plt.title("Average Salary Change % by Country")
plt.xlabel("Salary Change %")
plt.show()

"""SECTION 9: Top 15 Most At-Risk Job Roles"""

top_roles = (df.groupby("job_role")["automation_risk_percent"]
               .mean()
               .sort_values(ascending=False)
               .head(15)
               .sort_values(ascending=True))

plt.barh(top_roles.index, top_roles.values,
         color="tomato", edgecolor="white")
plt.title("Top 15 Most At-Risk Job Roles")
plt.xlabel("Avg Automation Risk %")
plt.show()

"""SECTION 10: AI Score Spread by Risk Category (Box Plot)"""

order  = ["Low", "Medium", "High"]
colors = ["#2ecc71", "#f0a500", "#e74c3c"]
data   = [df[df["automation_risk_category"] == r]["ai_replacement_score"].values for r in order]

bp = plt.boxplot(data, patch_artist=True, labels=order,
                 medianprops=dict(color="black", linewidth=2))
for patch, color in zip(bp["boxes"], colors):
    patch.set_facecolor(color)
plt.title("AI Replacement Score by Risk Category")
plt.ylabel("AI Replacement Score")
plt.show()

SECTION 11: Year-over-Year Trend

yearly = df.groupby("year").agg(
    automation_risk=("automation_risk_percent", "mean"),
    ai_score=("ai_replacement_score", "mean"),
    reskilling=("reskilling_urgency_score", "mean"),
).round(2)

plt.figure(figsize=(10, 4))
plt.plot(yearly.index, yearly["automation_risk"], marker="o", label="Automation Risk %", color="steelblue", linewidth=2)
plt.plot(yearly.index, yearly["ai_score"],         marker="s", label="AI Replace Score",  color="tomato",    linewidth=2)
plt.plot(yearly.index, yearly["reskilling"],        marker="^", label="Reskilling Urgency",color="orange",    linewidth=2)
plt.fill_between(yearly.index, yearly["automation_risk"], alpha=0.1, color="steelblue")
plt.title("Year-over-Year Trend — Key Metrics")
plt.ylabel("Score / %")
plt.xlabel("Year")
plt.xticks(yearly.index)
plt.legend()
plt.tight_layout()
plt.show()

"""SECTION 12: Reskilling Urgency Heatmap (Industry × Year)"""

pivot = df.pivot_table(index="industry", columns="year",
values="reskilling_urgency_score", aggfunc="mean").round(1)

sns.heatmap(pivot, annot=True, fmt=".1f", cmap="YlOrRd", linewidths=0.5)
plt.title("Reskilling Urgency Score — Industry × Year")
plt.show()

"""SECTION 13: Skill Gap vs AI Replacement Score (Scatter)"""

colors_map = {"Low": "green", "Medium": "orange", "High": "red"}

for risk, grp in df.groupby("automation_risk_category"):
    plt.scatter(grp["skill_gap_index"], grp["ai_replacement_score"],
                label=risk, color=colors_map[risk], alpha=0.4, s=12)
plt.title("Skill Gap Index vs AI Replacement Score")
plt.xlabel("Skill Gap Index")
plt.ylabel("AI Replacement Score")
plt.legend(title="Risk Category")
plt.show()

"""SECTION 14: Remote Feasibility Score by Industry"""

remote = df.groupby("industry")["remote_feasibility_score"].mean().sort_values(ascending=True)

plt.barh(remote.index, remote.values, color="mediumslateblue", edgecolor="white")
plt.title("Average Remote Feasibility Score by Industry")
plt.xlabel("Remote Feasibility Score")
plt.show()

"""SECTION 15: Wage Volatility by Risk Category"""

order  = ["Low", "Medium", "High"]
colors = ["green", "orange", "red"]
data   = [df[df["automation_risk_category"] == r]
["wage_volatility_index"].values for r in order]

bp = plt.boxplot(data, patch_artist=True, labels=order,
                 medianprops=dict(color="black", linewidth=2))
for patch, color in zip(bp["boxes"], colors):
    patch.set_facecolor(color)
plt.title("Wage Volatility Index by Risk Category")
plt.ylabel("Wage Volatility Index")
plt.show()

"""SECTION 16: Correlation Heatmap"""

df["industry_enc"] = pd.factorize(df["industry"])[0]
df["country_enc"] = pd.factorize(df["country"])[0]
df["risk_enc"] = pd.factorize(df["automation_risk_category"])[0]

corr_cols = [
    "automation_risk_percent", "ai_replacement_score",
    "skill_gap_index",
    "salary_change_percent", "remote_feasibility_score",
    "reskilling_urgency_score", "wage_volatility_index",
    "industry_enc", "country_enc", "risk_enc"
]

plt.figure(figsize=(10, 8))
sns.heatmap(df[corr_cols].corr(), annot=True, fmt=".2f", cmap="coolwarm",
            center=0, linewidths=0.5)
plt.title("Correlation Heatmap")
plt.show()

"""SECTION 17 — EDA Summary"""

print("=" * 45)
print("      EDA SUMMARY — AI Job Replacement")
print("=" * 45)
print(f"Total Records          : {len(df):,}")
print(f"Industries             : {df['industry'].nunique()}")
print(f"Countries              : {df['country'].nunique()}")
print(f"Job Roles              : {df['job_role'].nunique()}")
print(f"Year Range             : {df['year'].min()} → {df['year'].max()}")
print(f"Mean Automation Risk   : {df['automation_risk_percent'].mean():.2f}%")
print(f"Mean AI Replace Score  : {df['ai_replacement_score'].mean():.2f}")
print(f"Mean Skill Gap Index   : {df['skill_gap_index'].mean():.2f}")
print(f"Mean Salary Change     : {df['salary_change_percent'].mean():.2f}%")
print(f"Mean Reskilling Urgency: {df['reskilling_urgency_score'].mean():.2f}")
print(f"High Risk Records      : {(df['automation_risk_category']=='High').sum():,} ({(df['automation_risk_category']=='High').mean()*100:.1f}%)")
print(f"Most At-Risk Role      : {df.groupby('job_role')['automation_risk_percent'].mean().idxmax()}")
print(f"Most At-Risk Industry  : {df.groupby('industry')['ai_replacement_score'].mean().idxmax()}")
print("=" * 45)

"""SECTION 18: Classification(automation_risk_category)"""

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt

# ── Encode categorical columns ──────────────────────────────
le = LabelEncoder()
df["industry_enc"] = le.fit_transform(df["industry"])
df["country_enc"]  = le.fit_transform(df["country"])
df["job_role_enc"] = le.fit_transform(df["job_role"])

# ── Features and Target ─────────────────────────────────────
features = ["automation_risk_percent", "ai_replacement_score",
            "skill_gap_index", "salary_change_percent",
            "remote_feasibility_score", "reskilling_urgency_score",
            "wage_volatility_index", "industry_enc",
            "country_enc", "job_role_enc", "year"]

X = df[features]
y = df["automation_risk_category"]

# ── Train Test Split ─────────────────────────────────────────
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

# ── Train Model ──────────────────────────────────────────────
clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(X_train, y_train)

# ── Predictions ──────────────────────────────────────────────
y_pred = clf.predict(X_test)

# ── Accuracy ─────────────────────────────────────────────────
print("Accuracy:", accuracy_score(y_test, y_pred))
print()
print(classification_report(y_test, y_pred))

# ── Confusion Matrix ─────────────────────────────────────────
cm = confusion_matrix(y_test, y_pred, labels=["Low","Medium","High"])
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=["Low","Medium","High"],
            yticklabels=["Low","Medium","High"])
plt.title("Confusion Matrix — Classification")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.show()

# ── Feature Importance ───────────────────────────────────────
importance = pd.Series(clf.feature_importances_, index=features).sort_values()
plt.barh(importance.index, importance.values, color="teal", edgecolor="white")
plt.title("Feature Importance — Classification")
plt.xlabel("Importance Score")
plt.show()

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.neighbors import KNeighborsRegressor
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

# ── Encode categorical columns ──────────────────────────────
le = LabelEncoder()
df["industry_enc"] = le.fit_transform(df["industry"])
df["country_enc"]  = le.fit_transform(df["country"])
df["job_role_enc"] = le.fit_transform(df["job_role"])

# ── Features and Target ──────────────────────────────────────
features = ["ai_replacement_score", "skill_gap_index",
            "salary_change_percent", "remote_feasibility_score",
            "reskilling_urgency_score", "wage_volatility_index",
            "industry_enc", "country_enc", "job_role_enc", "year"]

X = df[features]
y = df["automation_risk_percent"]

# ── Train Test Split ─────────────────────────────────────────
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

"""SECTION 19: Linear Regression"""

# ── Train ────────────────────────────────────────────────────
lr = LinearRegression()
lr.fit(X_train, y_train)
y_pred_lr = lr.predict(X_test)

# ── Metrics ──────────────────────────────────────────────────
print("=" * 35)
print("     LINEAR REGRESSION")
print("=" * 35)
print(f"MSE : {mean_squared_error(y_test, y_pred_lr):.2f}")
print(f"R²  : {r2_score(y_test, y_pred_lr):.4f}")

# ── Graph ─────────────────────────────────────────────────────
plt.scatter(y_test, y_pred_lr, alpha=0.3, color="steelblue", s=10)
plt.plot([y_test.min(), y_test.max()],
         [y_test.min(), y_test.max()],
         color="red", linewidth=2, linestyle="--")
plt.title("Actual vs Predicted — Linear Regression")
plt.xlabel("Actual")
plt.ylabel("Predicted")
plt.show()

"""SECTION 20: Random Forest"""

# ── Train ────────────────────────────────────────────────────
rf = RandomForestRegressor(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)

# ── Metrics ──────────────────────────────────────────────────
print("=" * 35)
print("     RANDOM FOREST")
print("=" * 35)
print(f"MSE : {mean_squared_error(y_test, y_pred_rf):.2f}")
print(f"R²  : {r2_score(y_test, y_pred_rf):.4f}")

# ── Graph ─────────────────────────────────────────────────────
plt.scatter(y_test, y_pred_rf, alpha=0.3, color="teal", s=10)
plt.plot([y_test.min(), y_test.max()],
         [y_test.min(), y_test.max()],
         color="red", linewidth=2, linestyle="--")
plt.title("Actual vs Predicted — Random Forest")
plt.xlabel("Actual")
plt.ylabel("Predicted")
plt.show()

"""SECTION 21: Decision Tree"""

# ── Train ────────────────────────────────────────────────────
dt = DecisionTreeRegressor(random_state=42)
dt.fit(X_train, y_train)
y_pred_dt = dt.predict(X_test)

# ── Metrics ──────────────────────────────────────────────────
print("=" * 35)
print("     DECISION TREE")
print("=" * 35)
print(f"MSE : {mean_squared_error(y_test, y_pred_dt):.2f}")
print(f"R²  : {r2_score(y_test, y_pred_dt):.4f}")

# ── Graph ─────────────────────────────────────────────────────
plt.scatter(y_test, y_pred_dt, alpha=0.3, color="orange", s=10)
plt.plot([y_test.min(), y_test.max()],
         [y_test.min(), y_test.max()],
         color="red", linewidth=2, linestyle="--")
plt.title("Actual vs Predicted — Decision Tree")
plt.xlabel("Actual")
plt.ylabel("Predicted")
plt.show()

"""SECTION 22: KNN"""

# ── Train ────────────────────────────────────────────────────
knn = KNeighborsRegressor(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred_knn = knn.predict(X_test)

# ── Metrics ──────────────────────────────────────────────────
print("=" * 35)
print("     KNN")
print("=" * 35)
print(f"MSE : {mean_squared_error(y_test, y_pred_knn):.2f}")
print(f"R²  : {r2_score(y_test, y_pred_knn):.4f}")

# ── Graph ─────────────────────────────────────────────────────
plt.scatter(y_test, y_pred_knn, alpha=0.3, color="purple", s=10)
plt.plot([y_test.min(), y_test.max()],
         [y_test.min(), y_test.max()],
         color="red", linewidth=2, linestyle="--")
plt.title("Actual vs Predicted — KNN")
plt.xlabel("Actual")
plt.ylabel("Predicted")
plt.show()

"""SECTION 23: Comparison"""

# ── Compare all 4 models ─────────────────────────────────────
models    = ["Linear Regression", "Random Forest", "Decision Tree", "KNN"]
mse_scores = [
    mean_squared_error(y_test, y_pred_lr),
    mean_squared_error(y_test, y_pred_rf),
    mean_squared_error(y_test, y_pred_dt),
    mean_squared_error(y_test, y_pred_knn)
]
r2_scores = [
    r2_score(y_test, y_pred_lr),
    r2_score(y_test, y_pred_rf),
    r2_score(y_test, y_pred_dt),
    r2_score(y_test, y_pred_knn)
]

# R² Comparison
plt.bar(models, r2_scores, color=["steelblue","teal","orange","purple"],
        edgecolor="white")
plt.title("R² Score Comparison — All Models")
plt.ylabel("R² Score")
plt.ylim(0, 1.1)
for i, v in enumerate(r2_scores):
    plt.text(i, v + 0.01, f"{v:.4f}", ha="center", fontweight="bold")
plt.show()

# MSE Comparison
plt.bar(models, mse_scores, color=["steelblue","teal","orange","purple"],
        edgecolor="white")
plt.title("MSE Comparison — All Models")
plt.ylabel("MSE")
for i, v in enumerate(mse_scores):
    plt.text(i, v + 0.5, f"{v:.2f}", ha="center", fontweight="bold")
plt.show()

# Summary Table
print("=" * 55)
print(f"{'Model':<20} {'MSE':>10} {'R²':>10}")
print("=" * 55)
for m, mse, r2 in zip(models, mse_scores, r2_scores):
    print(f"{m:<20} {mse:>10.2f} {r2:>10.4f}")
print("=" * 55)